// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProduct(arg1:main.Product):Promise<void>;

export function CompleteSale(arg1:main.Sale):Promise<void>;

export function DeleteCategory(arg1:string):Promise<void>;

export function DeleteProduct(arg1:string):Promise<void>;

export function GetCategories():Promise<Array<main.Category>>;

export function GetProducts():Promise<Array<main.Product>>;

export function GetSales():Promise<Array<main.Sale>>;

export function RenameCategory(arg1:string,arg2:string):Promise<void>;

export function SaveCategory(arg1:main.Category):Promise<void>;

export function UpdateProduct(arg1:main.Product):Promise<void>;
